spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: root
  sql:
    init:
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
  application:
    name: spring-redis


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.jnu.devhub.model.dto, cn.edu.jnu.devhub.model.vo
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /
  ssl:
    key-store: classpath:keystore.p12
    key-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
    key-store-password: 123456



springdoc:
  api-docs:
    path: /api-docs